# Generated by Django 5.1.1 on 2024-09-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
